language: objective-c

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint
    - cd Example
    - pod install
    - cd ..
    - set -o pipefail
    - xcodebuild -workspace BPForms.xcworkspace -scheme 'BPFormsExample' -sdk iphonesimulator clean build | xcpretty -c
    - xcodebuild -workspace BPForms.xcworkspace -scheme 'BPFormsExample' -sdk iphonesimulator test | xcpretty -c
    - xcodebuild -workspace BPForms.xcworkspace -scheme 'BPForms' -sdk iphonesimulator clean build | xcpretty -c
    - xcodebuild -workspace BPForms.xcworkspace -scheme 'BPFormsFramework' -sdk iphonesimulator clean build | xcpretty -c